- hosts: node
  become: true
  tasks:
     - name: delete old deployment
       command: kubectl delete -f /s0/k8s_yaml/Deployment.yaml
     - name: delete old service
       command: kubectl delete -f /s0/k8s_yaml/Service.yaml
     - name: create new deployment
       command: kubectl apply -f /s0/k8s_yaml/Deployment.yaml
     - name: create new service
       command: kubectl apply -f /s0/k8s_yaml/Service.yaml

